import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export const exportToCSV = (transactions, budgets) => {
    // CSV Header
    let csvContent = "data:text/csv;charset=utf-8,";

    // Transactions Section
    csvContent += "--- TRANSACTIONS ---\n";
    csvContent += "Date,Type,Category,Amount,Description\n";
    (transactions || []).forEach(t => {
        const date = t.date ? format(new Date(t.date), 'yyyy-MM-dd') : 'N/A';
        const type = t.type || 'N/A';
        const category = t.category || 'Uncategorized';
        const amount = t.amount || 0;
        const desc = (t.description || '').replace(/,/g, ''); // prevent csv breaks
        csvContent += `${date},${type},${category},${amount},${desc}\n`;
    });

    csvContent += "\n--- BUDGETS ---\n";
    csvContent += "Category,Amount,Spent,Remaining\n";
    (budgets || []).forEach(b => {
        const category = b.category || 'N/A';
        const amount = b.amount || 0;
        const spent = b.spent || 0;
        const remaining = amount - spent;
        csvContent += `${category},${amount},${spent},${remaining}\n`;
    });

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `finance_report_${format(new Date(), 'yyyy-MM-dd')}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
};

export const exportToPDF = (transactions, budgets, user) => {
    const doc = new jsPDF();
    const userName = user?.name || 'Valued User';

    // Config
    const primaryColor = [44, 62, 80]; // Classic dark slate
    const accentColor = [127, 140, 141]; // Cool gray

    // Helper to format currency
    const formatCurr = (val) => `$${(parseFloat(val) || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

    let currentY = 20;

    // --- Header Section ---
    doc.setFont("helvetica", "bold");
    doc.setFontSize(28);
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text('FINANCE REPORT', 14, currentY);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
    currentY += 8;
    doc.text(`Generated by FinanceEra on ${format(new Date(), 'MMMM dd, yyyy')}`, 14, currentY);

    // Add a horizontal line
    currentY += 5;
    doc.setDrawColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.setLineWidth(0.5);
    doc.line(14, currentY, 196, currentY);

    // --- Account Info ---
    currentY += 12;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text('PREPARED FOR:', 14, currentY);

    doc.setFont("helvetica", "normal");
    currentY += 6;
    doc.text(userName, 14, currentY);
    if (user?.email) {
        currentY += 5;
        doc.text(user.email, 14, currentY);
    }

    // --- Summary Section ---
    const totalIncome = (transactions || []).filter(t => t.type === 'income').reduce((acc, t) => acc + (parseFloat(t.amount) || 0), 0);
    const totalExpenses = (transactions || []).filter(t => t.type === 'expense').reduce((acc, t) => acc + (parseFloat(t.amount) || 0), 0);
    const netSavings = totalIncome - totalExpenses;

    currentY += 15;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text('EXECUTIVE SUMMARY', 14, currentY);

    currentY += 6;
    autoTable(doc, {
        startY: currentY,
        head: [['Total Income', 'Total Expenses', 'Net Savings']],
        body: [[formatCurr(totalIncome), formatCurr(totalExpenses), formatCurr(netSavings)]],
        theme: 'plain',
        styles: { font: 'helvetica', fontSize: 11, halign: 'center' },
        headStyles: { fontStyle: 'bold', textColor: primaryColor, fillColor: [245, 247, 250], lineWidth: 0.1, lineColor: primaryColor },
        bodyStyles: { textColor: [40, 40, 40], lineWidth: 0.1, lineColor: primaryColor },
        margin: { top: 0, left: 14, right: 14 }
    });

    currentY = doc.lastAutoTable?.finalY + 15 || currentY + 30;

    // --- Budgets Section ---
    if (budgets && budgets.length > 0) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.text('BUDGET ANALYSIS', 14, currentY);

        currentY += 6;
        const budgetData = budgets.map(b => {
            const amt = parseFloat(b.amount) || 0;
            const spt = parseFloat(b.spent) || 0;
            const rem = amt - spt;
            return [
                b.category || 'Uncategorized',
                formatCurr(amt),
                formatCurr(spt),
                formatCurr(rem)
            ];
        });

        autoTable(doc, {
            startY: currentY,
            head: [['Category', 'Allocated Budget', 'Amount Spent', 'Remaining']],
            body: budgetData,
            theme: 'striped',
            styles: { font: 'helvetica', fontSize: 10 },
            headStyles: { fillColor: primaryColor, textColor: 255, fontStyle: 'bold' },
            alternateRowStyles: { fillColor: [248, 249, 250] },
            margin: { left: 14, right: 14 }
        });
        currentY = doc.lastAutoTable?.finalY + 15 || currentY + 20;
    }

    // --- Transactions Section ---
    if (transactions && transactions.length > 0) {
        // Ensure we don't start the transaction table too low, causing a weird break
        if (currentY > 230) {
            doc.addPage();
            currentY = 20;
        }

        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        doc.text('TRANSACTION LEDGER', 14, currentY);

        currentY += 6;
        const transactionData = transactions.map(t => [
            t.date ? format(new Date(t.date), 'MMM dd, yyyy') : 'N/A',
            t.description || t.category || 'Transaction',
            t.category || 'Uncategorized',
            t.type === 'income' ? 'Credit' : 'Debit',
            formatCurr(t.amount)
        ]);

        autoTable(doc, {
            startY: currentY,
            head: [['Date', 'Description', 'Category', 'Type', 'Amount']],
            body: transactionData,
            theme: 'grid',
            styles: { font: 'helvetica', fontSize: 9, cellPadding: 3 },
            headStyles: { fillColor: primaryColor, textColor: 255, fontStyle: 'bold' },
            bodyStyles: { textColor: [50, 50, 50] },
            columnStyles: {
                0: { cellWidth: 30 },
                3: { cellWidth: 25 },
                4: { cellWidth: 30, halign: 'right' }
            },
            margin: { left: 14, right: 14 }
        });
    }

    // --- Page Footers ---
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFont("helvetica", "italic");
        doc.setFontSize(8);
        doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
        doc.setDrawColor(accentColor[0], accentColor[1], accentColor[2]);
        doc.setLineWidth(0.2);
        doc.line(14, 285, 196, 285);
        doc.text(`Page ¹/¼${i} of ${pageCount}`, 196, 290, { align: 'right' });
        doc.text('Confidential Financial Document', 14, 290);
    }

    // Save the PDF
    doc.save(`Finance_Report_${format(new Date(), 'yyyyMMdd')}.pdf`);
};
